import {
  HomeIcon,
  UsersIcon,
  CreditCardIcon,
  CogIcon,
  EyeIcon,
  PencilIcon,
  PencilSquareIcon,
  TrashIcon,
  UserIcon, 
  ShoppingBagIcon,
  ReceiptPercentIcon,
  SpeakerWaveIcon,
  LinkIcon,
  PhotoIcon,
  BellIcon,
  PaperAirplaneIcon,
  ChatBubbleBottomCenterTextIcon,
  DocumentTextIcon,
  CheckIcon,
  ShoppingCartIcon,
  TagIcon,
  CubeIcon,
  ClipboardDocumentListIcon,
  PlusIcon,
  MinusIcon,
  StarIcon,
  FireIcon,
  ArrowTrendingUpIcon,
  ExclamationTriangleIcon,
  ArrowPathIcon,
  CurrencyDollarIcon,
  ArrowLeftIcon,
  XMarkIcon,
  UserGroupIcon,
  CheckCircleIcon,
  ClockIcon,
  UserCircleIcon,
  MagnifyingGlassIcon,
  FunnelIcon,
  BoltIcon
} from "@heroicons/react/24/outline";

export {
  HomeIcon,
  UsersIcon,
  CreditCardIcon,
  CogIcon,
  EyeIcon,
  PencilIcon,
  PencilSquareIcon,
  TrashIcon,
  UserIcon,
  ShoppingBagIcon,
  ReceiptPercentIcon as ReceiptTaxIcon,
  SpeakerWaveIcon as SpeakerphoneIcon,
  LinkIcon,
  PhotoIcon as PhotographIcon,
  BellIcon,
  PaperAirplaneIcon,
  ChatBubbleBottomCenterTextIcon as ChatAltIcon,
  DocumentTextIcon,
  CheckIcon,
  ShoppingCartIcon,
  TagIcon,
  CubeIcon,
  ClipboardDocumentListIcon as ClipboardListIcon,
  PlusIcon,
  MinusIcon,
  StarIcon,
  FireIcon,
  ArrowTrendingUpIcon as TrendingUpIcon,
  ExclamationTriangleIcon,
  ArrowPathIcon,
  CurrencyDollarIcon,
  ArrowLeftIcon,
  XMarkIcon,
  UserGroupIcon,
  CheckCircleIcon,
  ClockIcon,
  UserCircleIcon,
  MagnifyingGlassIcon as SearchIcon,
  FunnelIcon,
  BoltIcon,
};
